### PR TITLE
Add Jason's CI commits 

### PR DESCRIPTION
**Pull request by hdoupe**
Separates some of the CI commits @jdebacker added in #80, since the actions aren't running there for some reason.

### CODE REVIEW

**Comment by hdoupe** [comment]
Hmmm, not running on this branch either....

**Comment by jdebacker** [comment]
@hdoupe I'm still unsure why the GH Action is not being run here.  Maybe check: Settings -> Action permissions -- are settings there ok?

**Comment by hdoupe** [comment]
Hmmm, looks ok to me:

image

**Comment by jdebacker** [comment]
@hdoupe thanks for checking.  Looks ok to me.  Still puzzled.  All questions I see this on internet seem to be idiosyncratic and "it just started working".  Should we just try to merge this PR and see if it runs on a subsequent one?

**Comment by hdoupe** [comment]
@jdebacker closing #81 in favor of #82. I used the Actions tab to create the action and copy and pasted your work flow file. For some reason, that worked. :man_shrugging:

**Pull request closed without merging**
