### PR TITLE
Refactor quantity_response using pch_response function, and add labor_response

### PR DESCRIPTION
**Pull request by MaxGhenis**
This PR makes the following changes:
1. Adds a `pch_response` function which multiplies an elasticity by the change in two variables. This reduces code duplication in `quantity_response`, and also ensures that arrays are accepted, resolving https://github.com/PSLmodels/Behavioral-Responses/issues/56.
2. Refactors `quantity_response` to use `pch_response`. It now just calculates the substitution and income effects separately and returns the sum.
3. Adds default values to `quantity_response` of 1 for `quantity` and 0 for all other inputs. They're all set as numpy arrays to work when used with arrays. This resolves https://github.com/PSLmodels/Behavioral-Responses/issues/57.
4. Adds a new `labor_response` function which translates the `quantity_response` inputs into a more typical form for simulating a labor response. This changes the parameter names, and also accepts MTRs rather than after-tax prices (which would be marginal net-of-tax rates), passing `1-mtr`.

[This notebook](https://colab.research.google.com/drive/148zANwAiQIuyMno9behv3WgIoAK89vLy) contains examples of `labor_response`, showing in particular how arrays can be passed to it.

### CODE REVIEW

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for submitting Behavioral-Responses pull request #58.
Can you post a comment in this conversation that shows how Tax-Calculator Python Cookbook [recipe 4](https://pslmodels.github.io/Tax-Calculator/cookbook.html#recipe04) would be rewritten if PR #58 were merged into the master branch?  Thanks.

Also, note that PR #58 has conflicts (in the `behresp/__init__.py` file) that need to be resolved.

**Comment by MattHJensen** [comment]
@MaxGhenis, just want to chime in w more thanks for opening this PR. Is this something you are still interested in advancing?

**Comment by MaxGhenis** [comment]
Sorry I let this sit. I tested recipe04 [here](https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/recipes/recipe04.ipynb) and found that it produces identical results to the current script (in general this is backwards-compatible). I also resolved the conflicts in `__init__.py`.

I think this is ready to merge.

**Comment by MattHJensen** [comment]
Thanks a lot @MaxGhenis. 

@martinholmer, does @MaxGhenis's [answer](https://github.com/PSLmodels/Behavioral-Responses/pull/58#issuecomment-527990030) address your [questions](https://github.com/PSLmodels/Behavioral-Responses/pull/58#issuecomment-491905392)? 

Any other questions or feedback for Max before I merge this?

**Comment by martinholmer** [comment]
@MattHJensen asked:
> does @MaxGhenis's [answer](https://github.com/PSLmodels/Behavioral-Responses/pull/58#issuecomment-527990030) address your [questions](https://github.com/PSLmodels/Behavioral-Responses/pull/58#issuecomment-491905392)? 

Yes @MaxGhenis provided an example and fixed the bug in this PR,
But if the idea of this PR is to simplify Tax-Calculator recipe04, then I don't see the Tax-Calculator pull request that does that.

**Comment by MaxGhenis** [comment]
The idea wasn't necessarily to simplify recipe04, but to add capabilities described in the PR description.

But, I think it can simplify, or at least add another approach to executing, recipe04. I'll look into this today.

**Comment by MaxGhenis** [comment]
Here's a [simplified version](https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/recipes/recipe04.ipynb) of recipe04 using the new vectorized `quantity_response`, which produces identical results (except rounding to 3 digits in all columns).

The important change is in cell 7, where the response is calculated for each row in the original dataframe based on each record's features.

To facilitate this, the elasticities are assigned per record in cell 6.

From there, I did the aggregation using standard pandas groupby and sums, rather than within a loop as was previously needed to model heterogenerous elasticities. It then prints a final dataframe, rather than printing tab-separated values.

Here's the [code](https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/recipes/recipe04.py) as a `.py` file. The number of lines is about the same as the original, but it's a clearer more pandas-Pythonic approach IMO.

**Comment by MattHJensen** [comment]
@MaxGhenis, thanks for the example of how these changes could be used in Tax-Calculator's Recipe 4. 

Given that simplifying Recipe 4 is not the core purpose of this PR, though, do you mind opening an issue or PR in Tax-Calculator for further discussion? I will be happy to review over there when that issue or PR is open, and I imagine @martinholmer may have some comments as well since he asked the question about the application of these changes to Recipe 4. 

In the meantime, thanks very much for your work on this PR and clear issues explaining its purpose. Merging.

**Pull request merged**
