### PR TITLE
Remove ltcg from ETI substitution effect base. 

### LINKED ISSUE #36: Should CG income be included in the base for calculating ETI substitution effect?
Currently the substitution effect is calculated using taxable income (c04800) as the base. See https://github.com/PSLmodels/Behavioral-Responses/blob/master/behresp/behavior.py#L199. 

If one were to apply both a non-zero substitution elasticity and a non-zero long-term capital gains elasticity, does it mean that we are double counting some behavior? 

And if so, would a reasonable solution be to remove LTCG from the substitution effect by subtracting it from c04800 prior to the calculation of the substitution effect?

If one were to model short-term capital gains separately, would STCG also need to be subtracted from c04800 prior to the calculation of the substitution effect? 

--

This is related to https://github.com/PSLmodels/Tax-Calculator/issues/2189, so cc @andersonfrailey @codykallen @maxghenis. 

This is related to https://github.com/PSLmodels/Tax-Calculator/issues/2180, so cc @evtedeschi3 @martinholmer. 

Given Dan's familiarity with the ETI literature, cc @feenberg.

### PR DESCRIPTION
**Pull request by MattHJensen**
Resolves #36. 

- [x] needs documentation update to explain divergence from ETI literature.

### CODE REVIEW

**Comment by MattHJensen** [comment]
This is ready for review.

**Comment by martinholmer** [comment]
@MattHJensen said in Behavioral-Responses issue #36:
> If one were to apply both a non-zero substitution elasticity and a non-zero long-term capital gains elasticity, does it mean that we are double counting some behavior?
>
> And if so, would a reasonable solution be to remove LTCG from the substitution effect by subtracting it from c04800 prior to the calculation of the substitution effect?

I know very little about the ETI research literature, but there seem to me a disconnect between what you said in #36 and the code change you propose in #37.  Your statement above suggests that the double-counting occurs only when assuming "a non-zero substitution elasticity and a non-zero long-term capital gains elasticity."   And by proposing #37 you have answered your first question with a yes.  

So, why not revise the code to subtract LTCG out of the taxable income measure used to compute the substitution effect **only** when there is a non-zero LTCG elasticity.  Why deviate from the ETI research literature in situations where there is no double-counting?

**Comment by MattHJensen** [comment]
> I know very little about the ETI research literature, but there seem to me a disconnect between what you said in #36 and the code change you propose in #37. Your statement above suggests that the double-counting occurs only when assuming "a non-zero substitution elasticity and a non-zero long-term capital gains elasticity." And by proposing #37 you have answered your first question with a yes.

> So, why not revise the code to subtract LTCG out of the taxable income measure used to compute the substitution effect only when there is a non-zero LTCG elasticity. Why deviate from the ETI research literature in situations where there is no double-counting?

You're right to spot the disconnect between this PR and my concern about double counting in #36. 

There was no overriding factor that caused me to remove the ETI from the substitution effect base even when the ltcg response was zero, but a few factors, together, pushed me over the edge:

1. It is generally confusing for the definition of a parameter to depend on the state of other parameters.
2. I often think of Behavioral-Responses as a tool to predict what the official estimators (JCT/Treasury/CBO) will say about a reform, and as far as I know, all of them use a separate CG elasticity. 
3. I was in the middle of analyzing a proposal where the pure ETI-literature-derived substitution effect was producing counterintuitive results, aside from the double counting. Consider a tax unit with only long term capital gains and no wage income. Congress hikes the MTR wrt wage income, without changing the MTR wrt CG income. If CG is in the base for the substitution effect calculation, that tax unit will see a big decrease in taxable income. 
4. Seeing that the LTCG elasticity is set at 0 by default, some users might assume that means there is no LTCG-related behavioral effect when the substitution effect parameter is positive. .

**Comment by martinholmer** [comment]
@MattHJensen,  Thanks for the extensive explanation of the thinking behind B-R PR #37.  All this makes sense, so I have no objections to merging this change.  Although if none of the tests failed, it would suggest adding one that would have failed would be a good idea.  I guess we need a test that assumes both the substitution and LTCG elasticities are non-zero.

**Comment by MattHJensen** [comment]
> Although if none of the tests failed, it would suggest adding one that would have failed would be a good idea. I guess we need a test that assumes both the substitution and LTCG elasticities are non-zero.

Yea, this makes sense. I'll add one to the PR.

**Comment by martinholmer** [comment]
@MattHJensen, Why does commit 828d1d3 add the return of a Calculator object?
This is a major change in the Behavioral-Responses API that you are proposing without offering any rationale.

**Comment by MattHJensen** [comment]
> @MattHJensen, Why does commit 828d1d3 add the return of a Calculator object?
This is a major change in the Behavioral-Responses API that you are proposing without offering any rationale.

I am still working on this PR. I'll start a discussion of the changes when they're ready for review. In the meantime, I'll add back the WIP tag to show that I'm in progress on the testing.

**Comment by MattHJensen** [comment]
This PR is ready for review. 

In addition to addressing #36 and adding a test that fails under master but passes on this branch, the PR makes a substantial change to the behresp API by returning the calc2 with behavior calculator from `response()`.

Here is my thinking for returning calc2_beh:

- In order to conduct the original exploratory analysis to determine that #36 was a problem, I needed to look at how behresp was acting on individual records, and so I was working with a modified fork of Behavioral-Responses that returned the calculator. 
- It was taking me a long time to figure out how to write a failing test for this problem w/o being able to look at the microdata, but it is easy with the microdata and I was able to do so quickly.
- We have seen many users take advantage of the `tc` dump capabilities. Without returning the calculator, I don't know how users could do similar work with Behavioral-Responses.
- I have seen another user modify a fork of Behavioral-Responses to return the calculator object in order to try to figure out what is going on in the microdata. 

I do not know what kind of performance benchmarks Behavioral-Responses is trying to hit or the reason for those benchmarks, so I have not yet considered performance in these changes. One simple approach to alleviate some performance concerns -- which we may also want to adopt in the absence of performance concerns -- might be to have `response()` only return the calc2 w/behavior dataframe and add a new function to only return the two distribution table dataframes.

**Comment by martinholmer** [comment]
@MattHJensen,  I'm moving this week, so I will not be able to respond to [your ideas about Behavioral-Responses API changes](https://github.com/PSLmodels/Behavioral-Responses/pull/37#issuecomment-458150031) until early February.  Meanwhile, please leave PR #37 open for review by others.  When I am able to review this PR, it would be helpful to know exactly what you mean by "figure out what is going on in the microdata" when you say:
> I have seen another user modify a fork of Behavioral-Responses to return the calculator object in order to try to figure out what is going on in the microdata.

**Comment by andersonfrailey** [comment]
I've been doing what @MattHJensen mentioned here:
>I have seen another user modify a fork of Behavioral-Responses to return the calculator object in order to try to figure out what is going on in the microdata.

I was working with Behavioral-Response a few weeks ago and I wanted to look at some of the data that isn't included in the distribution table DataFrame that gets returned by the response function. To do this I modified the response function to return `calc2_behv` rather than `df2`. I basically just took this section:
```python
df2 = calc2_behv.distribution_table_dataframe()
del calc2_behv
# Return the two dataframes
return (df1, df2)
```
and turned it into:
```python
return calc2_behv
```

I've been thinking of opening an issue to talk about modifying the API to return the full calculator like the Behavior class used to before being removed from the Tax-Calculator package but haven't gotten around to it yet. I like the idea of `response` returning the full calculator. Then the user can use the functionality already built into Tax-Calculator perform all their analysis.

**Comment by martinholmer** [comment]
@andersonfrailey said in B-R PR #37:
> I was working with Behavioral-Responses a few weeks ago and I wanted to look at some of the data that isn't included in the distribution table DataFrame that gets returned by the response function. 

OK.  What kinds of data were you wanting to look at?  And what were you interested in doing with the variables that are not included in the distribution table DataFrame?

I'm asking because the `response` function should be designed in a safe way that supports the data needs of users.  But it is not easy to redesign the `response` function in a safe way without knowing what data (beyond the 22 variables in the distribution table DataFrame) users are interested in looking at.  Maybe we should add an optional parameter to the `responses` function that causes it to return **all** the variables (like the `tc --dump` option does) instead of just the 22 variables in the distribution table DataFrame.  Would the presence of such an option have met your needs for more data?  It would seem it would have met @MattHJensen's needs in developing the new test.

**Comment by martinholmer** [comment]
@MattHJensen, it would seem that pull request #37 contains far more than a resolution of issue #36.
I suggest that issue #38 --- the need for more response data --- be resolved in a different pull request after the  discussion in #38 is finished.  Meanwhile, can you refocus #37 on resolving #36?  If you do that, I'll be happy to merge it because there would be no API change in #37.

**Comment by MattHJensen** [comment]
> Meanwhile, can you refocus #37 on resolving #36? If you do that, I'll be happy to merge it because there would be no API change in #37.

@martinholmer, I was not able to devise an adequate test for #36 (by adequate, I mean one that fails on master) without returning extra data. I am happy to remove the testing for now and open an issue for adding tests after #38 is resolved. Is that what you are suggesting?

**Comment by martinholmer** [comment]
@MattHJensen said:
> I was unable to devise an adequate test for #36 (by adequate, I mean one that fails on master) without returning extra data. I am happy to remove the testing for now and open an issue for adding tests after #38 is resolved. Is that what you are suggesting?

I don't understand.  The core change in #37 causes a change (for some people) in the high-level data now returned from the `response` function, right?  I can understand that finding one of those "some people" could have been made easier for you if the `response` function had the option of returning more data.  But once you've found such a person, why does the test need the API change?

**Comment by MattHJensen** [comment]
This PR is ready for review.

**Comment by martinholmer** [comment]
@MattHJensen, Maybe I'm distracted by all the things going on with the move today, but I don't understand the new test.  

**First**, I don't understand the role of the new `behresp/tests/rec_only_ltcg_inc.csv` file.  I couldn't seem to find where it's used.  Here's the file I'm talking about:

screen shot 2019-01-29 at 12 30 21 pm

**Second**, I don't understand this new `behresp/tests/rec_w_wo_ltcg.csv` file:

screen shot 2019-01-29 at 12 33 39 pm

How can a single individual (`MARS`=1) have positive spouse earnings (`e00200s`)?
Should I add data checking to Tax-Calculator so that it stops when people inadvertently enter data like this?

**Comment by martinholmer** [comment]
@MattHJensen,  Thanks for all your work on Behavioral-Responses pull request #37.  All the coding-style and substantive tests ran fine on my computer.  Sorry the limited output from the `response` function made your work more difficult, but we're discussing how best to remedy this situation in issue #38.

**Comment by MattHJensen** [comment]
@martinholmer, thanks a lot for reviewing/shepherding/merging this PR.

**Pull request merged**
