### PR TITLE
Release 0.11.0

### LINKED ISSUE #73: Suggestion regarding python versions
I ran into an issue when installing behresp to my personal computer. Specifically, it is incompatible with Python 3.8. Ultimately, I got everything to work by setting the python version in taxcalc virtual environment to 3.7.

I don't know what the best practices are with respect to python versions, but it might be worth while to either 1) update behresp to work with the newest version or 2) instruct users in how to set their python version so that everything works.

### PR DESCRIPTION
**Pull request by MattHJensen**
Add release notes for 0.11.0. 

The release will resolve #73. 

cc @jdebacker

### CODE REVIEW

**Comment by MattHJensen** [comment]
@jdebacker, @hdoupe, @MaxGhenis, anyone else: 

Any idea how to keep these Travis CI builds from being queued and then never proceeding?

**Comment by hdoupe** [comment]
@MattHJensen If you click details on the pending request and wind up on this page

Screenshot from 2020-09-09 10-24-45

and then click on one of the job links ([233.1](https://travis-ci.com/github/PSLmodels/Behavioral-Responses/jobs/378752857), [233.2](https://travis-ci.com/github/PSLmodels/Behavioral-Responses/jobs/378752858), [233.3](https://travis-ci.com/github/PSLmodels/Behavioral-Responses/jobs/378752859)), then you wind up on a page like this that says that the build has passed:

Screenshot from 2020-09-09 10-27-04


You could try re-building doing something like:

```
git commit -m "Force rebuild" --allow-empty
git push upstream 0-11-0
```

**Comment by MaxGhenis** [comment]
Just bumping this up, as the lack of Python 3.8 support is breaking `behresp` in Colab notebooks ([example](https://colab.research.google.com/drive/1JZRCUr_Nfzte-xtypd7sRqLv8NneuCIl?usp=sharing)).

**Comment by MattHJensen** [comment]
Thanks @MaxGhenis for checking on this. I just published the release and conda packages.

**Pull request merged**
