### PR TITLE
Bump version to include 3.8

### PR DESCRIPTION
**Pull request by jdebacker**
This PR allows the `behresp` package to be built in Python 3.8 and for unit tests to be run on Python 3.8 (as well as 3.7 and 3.6).

### CODE REVIEW

**Comment by jdebacker** [comment]
The Travis CI tests will fail until there is a new `taxcalc` package on the PSL Anaconda channel that is built for Python 3.8.

**Comment by jdebacker** [comment]
@MattHJensen I'm having test failures where values returned aren't the expected hardcoded values in the tests.  I haven't changed any logic here.  Could it be that these differences are due to a different Tax-Calculator version than the expected values were pulled from?  Changes in the CPS data used?

**Comment by MattHJensen** [comment]
@jdebacker, thanks for noting this. I doubt the issue is CPS given that the subsample is specified in the test. It might be pandas or Tax-Calculator. I will also do a little investigation.

**Comment by jdebacker** [comment]
@MattHJensen Thanks for the follow up - I can poke around and see if it is anything related to recent changes to Pandas and Numpy.  Just wasn't sure if you might know offhand what this could be.

**Comment by jdebacker** [comment]
I've tested locally on Pandas 1.1.0 and 1.01 -- both Pandas versions return the same values, which do not match the expected values in the four failed tests.

**Comment by MattHJensen** [comment]
@jdebacker, thanks for the pandas and numpy investigation. It looks like the expected results were last updated on June 28, 2019 for Tax-Calculator 2.4.2 by Martin. Since then, there have been a few updates to Tax-Calculator that have affected Tax-Calculator results and may have affected results here too: https://github.com/PSLmodels/Tax-Calculator/commits/master/taxcalc/tests/pufcsv_agg_expect.csv. I am trying to pinpoint which Tax-Calculator changes would have affected this particular cps subsample  is so we feel confident to update the expected results.

**Comment by MattHJensen** [comment]
Current hypothesis is that the changes stem from https://github.com/PSLmodels/Tax-Calculator/pull/2388. The way to test would be to run BR with taxcalc 2.6.0 and taxcalc 2.7.0, where the change was introduced: https://github.com/PSLmodels/Tax-Calculator/blob/d30efee5163439c24065438ee3cafdf9adf00ed7/docs/about/releases.md#2019-12-13-release-270. 

I've been working in the front seat of my car too long (power is still out), but may try to do that later if you don't get there first. Given that there have been no logic changes in BR since the tests were last updated, I am also ok updating the test results without exactly pinpointing where the difference came from, either in this PR or a separate dedicated PR.

**Comment by jdebacker** [comment]
@MattHJensen I installed TC 2.6 and all tests passed on this branch.  I installed TC 2.7 and 3 tests fail in `test_behavior`.  They also return different results than with TC 2.9.

As you note, since no changes in logic to `behresp`, I'm going to update the hard coded expected values in the tests to be consistent with TC 2.9.0.

**Comment by jdebacker** [comment]
Tests above were using Pandas 1.0.5. Tried to do a `conda update pandas` and conda updated Numpy to 1.19, but no version change for pandas.  Installed TC 2.9 to run tests and see output so that I could change the expected values in `test_behavior.py` and tests pass!  No idea what is going on. Here they are passing on TC 2.6, 2.7, and 2.9:

```
(behresp-dev) jason.debacker@x86_64-apple-darwin13 behresp % conda install -c pslmodels taxcalc==2.6.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jason.debacker/anaconda3/envs/behresp-dev

  added / updated specs:
    - taxcalc==2.6.0


The following packages will be DOWNGRADED:

  taxcalc                                      2.9.0-py37_0 --> 2.6.0-py37_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(behresp-dev) jason.debacker@x86_64-apple-darwin13 behresp % pytest
============================= test session starts ==============================
platform darwin -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /Users/jason.debacker/repos/Behavioral-Responses, inifile: pytest.ini
plugins: arraydiff-0.3, remotedata-0.3.2, doctestplus-0.4.0, openfiles-0.4.0
collected 16 items

tests/test_4package.py ..                                                [ 12%]
tests/test_behavior.py ......ssssssss                                    [100%]

======================== 8 passed, 8 skipped in 19.55s =========================
(behresp-dev) jason.debacker@x86_64-apple-darwin13 behresp % conda install -c pslmodels taxcalc==2.7.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jason.debacker/anaconda3/envs/behresp-dev

  added / updated specs:
    - taxcalc==2.7.0


The following packages will be UPDATED:

  taxcalc                                      2.6.0-py37_0 --> 2.7.0-py37_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(behresp-dev) jason.debacker@x86_64-apple-darwin13 behresp % pytest
============================= test session starts ==============================
platform darwin -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /Users/jason.debacker/repos/Behavioral-Responses, inifile: pytest.ini
plugins: arraydiff-0.3, remotedata-0.3.2, doctestplus-0.4.0, openfiles-0.4.0
collected 16 items

tests/test_4package.py ..                                                [ 12%]
tests/test_behavior.py ......ssssssss                                    [100%]

======================== 8 passed, 8 skipped in 20.08s =========================
(behresp-dev) jason.debacker@x86_64-apple-darwin13 behresp % conda install -c pslmodels taxcalc==2.9.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jason.debacker/anaconda3/envs/behresp-dev

  added / updated specs:
    - taxcalc==2.9.0


The following packages will be UPDATED:

  taxcalc                                      2.7.0-py37_0 --> 2.9.0-py37_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(behresp-dev) jason.debacker@x86_64-apple-darwin13 behresp % pytest
============================= test session starts ==============================
platform darwin -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /Users/jason.debacker/repos/Behavioral-Responses, inifile: pytest.ini
plugins: arraydiff-0.3, remotedata-0.3.2, doctestplus-0.4.0, openfiles-0.4.0
collected 16 items

tests/test_4package.py ..                                                [ 12%]
tests/test_behavior.py ......ssssssss                                    [100%]

======================== 8 passed, 8 skipped in 19.52s =========================
(behresp-dev) jason.debacker@x86_64-apple-darwin13 behresp %
```

I'm now thoroughly confused as to what is going on, but also a bit suspicious about conda managing packages as I thought and not sure why I can't update to Pandas 1.1.0 in my `behresp-dev` environment.

**Comment by jdebacker** [comment]
Switched to my base environment and did a `conda update --all`.  Got the latest Numpy and Pandas, TC 2.9 from Anaconda.  Updated values in `test_behavior.py` so that the 3 failing tests:
```
FAILED tests/test_behavior.py::test_nondefault_response_function[-0.1] - asse...
FAILED tests/test_behavior.py::test_nondefault_response_function[0.0] - asser...
FAILED tests/test_behavior.py::test_alternative_behavior_parameters - assert ...
```
now pass.  They also pass on TC built from master.

**Comment by jdebacker** [comment]
Ok - still failure on CI.

After updating all packages in my base env and having tests pass with TC 2.9 and TC from master, I then installed TC 2.6 (test failed), TC 2.7 (tests failed).  Then went back to TC 2.9, tests pass:
```
(base) jason.debacker@x86_64-apple-darwin13 behresp % pytest
============================= test session starts ==============================
platform darwin -- Python 3.7.7, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /Users/jason.debacker/repos/Behavioral-Responses, inifile: pytest.ini
collected 16 items

tests/test_4package.py ..                                                [ 12%]
tests/test_behavior.py ......ssssssss                                    [100%]

======================== 8 passed, 8 skipped in 26.49s =========================
(base) jason.debacker@x86_64-apple-darwin13 behresp % conda list taxcalc
conda list pandas# packages in environment at /Users/jason.debacker/anaconda3:
#
# Name                    Version                   Build  Channel
taxcalc                   2.9.0                     dev_0    <develop>
```

I do not know what is going on!  Note that my version of Pandas and Numpy were bumped down after downgrading my TC version.

**Comment by jdebacker** [comment]
@MattHJensen I've updated the expected results in `tests/test_behavior.py` to be consistent with TC 3.0.0.

I have been unable to get the Travis CI tests to pass with the `--pycodestyle` option.  Will work to try to get that back in...

**Comment by jdebacker** [comment]
@MattHJensen this PR is ready for your review.

**Comment by MattHJensen** [comment]
@jdebacker, thanks for adding Python 3.8 testing and updating the tests results! This LGTM. Merging now.

**Pull request merged**
